### PR TITLE
Fix/0x

### PR DESCRIPTION
**Pull request by H34D**
## Description

Rolled back most of the changes adding `0x` to assetId and serviceAgreementId
Added better DID handling

## Is this PR related with an open issue?

Related to Issue #84

### CODE REVIEW

**Comment by diminator** [comment]
LGTM!

**Comment by ssallam** [comment]
My opinion is that the 0x prefix is not the issue. The standard in representing hex values is to use a 0x prefix.

**Comment by ssallam** [comment]
And now squid-py and squid-js are not compatible.

**Comment by H34D** [comment]
> And now squid-py and squid-js are not compatible.

https://github.com/oceanprotocol/squid-py/issues/159

**Pull request merged**
