### PR TITLE
v2: Web3.js 1.2.3

### PR DESCRIPTION
**Pull request by kremalicious**
- refactoring for the new typings in web3.js 1.2.2
- introduces `esModuleInterop` again
- pass `Ocean` instead of `Web3` to `ddo.addProof()` method
- fresh `package-lock.json` to solve web3 dependency issues

Almost everything works:

- [x] passed integration tests against v2 Spree
- [x] passed manual QA against Commons
- [x] passed unit tests

As of right now, the `ContractEvent` unit test is failing with `Error: Transaction ran out of gas. Please provide more gas` at this point https://github.com/oceanprotocol/squid-js/blob/v2-web3-1.2.2/test/keeper/ContractEvent.test.ts#L24

The `test/keeper/TestContractHandler.ts` file is most likely the culprit, some things have changed in upstream `web3-eth-contract` and it's `Contract` export.

- https://github.com/oceanprotocol/squid-js/blob/v2-web3-1.2.2/test/keeper/TestContractHandler.ts

### CODE REVIEW

**Comment by H34D** [comment]
it is a known bug in the latest version of web3js: https://github.com/ethereum/web3.js/issues/3175

**Comment by H34D** [comment]
i would recommend keeping the code as is and not apply the patch. Wait for web3 to fix it.

**Comment by kremalicious** [comment]
@H34D amazing! Thanks for the investigation, we'll keep this PR open then and wait for fix

**Comment by H34D** [comment]
i expect v1.2.3 soon: https://github.com/ethereum/web3.js/pull/3203

**Pull request merged**
