### PR TITLE
Add status method to agreements module.

### PR DESCRIPTION
**Pull request by Pedro-vk**
## Description

Add status method to agreements module.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [x] Documentation

#### Funny gif

Put a link of a funny gif inside the parenthesis-->

### CODE REVIEW

**Comment by Pedro-vk** [comment]
@ssallam I think that is important to add the DID, agreement ID and service definition ID, because we are going to cover all the different uses cases. With the current API definition, we only covering and assuming that `EscrowAccessSecretStoreTemplate` is the unique way to use squid.

**Comment by ssallam** [comment]
> @ssallam I think that is important to add the DID, agreement ID and service definition ID, because we are going to cover all the different uses cases. With the current API definition, we only covering and assuming that `EscrowAccessSecretStoreTemplate` is the unique way to use squid.

To get the status of agreement, DID and Service Definition Id are not necessary, you can get did associated with the agreement id from the AgreementStoreManager contract.

`AgreementStoreManager.getAgreement(agreement_id)` -> 
```
                did,
                agreement.owner,
                agreement.template_id,
                cond_ids,
                agreement.updated_by,
                agreement.block_number_updated
```

**Comment by Pedro-vk** [comment]
And how can we know which condition ID is each one?

**Comment by ssallam** [comment]
Using template_id you will know which template is used, and the template specifies the conditions and order.

**Pull request merged**
